TA-161-Consumer Pact for Div-CMS interaction with CoreCaseDataApi
hmcts/div-case-maintenance-service pull request #375
Opened 2020-11-17 09:10 UTC by kasi-subramaniam

TA-161-Consumer Pact for Div-CMS interaction with CoreCaseDataApi

2020-11-18 08:46 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceReadForCaseWorker.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 requested changes
Please see comments for minor changes otherwise really good work here

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceReadForCitizen.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_citizen")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceSearchCases.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceSearchForCitizen.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_citizen")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceStartEventForCaseWorker.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceStartEventForCaseWorker.java
> +            .given("A StartEvent for Caseworkder is  requested")
Fix spelling mistake here please

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceStartEventForCitizen.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_citizen")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceStartForCaseWorker.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceStartForCitizen.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_for_citizen")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceSubmitEventForCaseWorker.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceSubmitEventForCitizen.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_citizen")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-11-18 08:53 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DivorceCaseMaintenanceSubmitForCaseWorker.java
> +    @Pact(provider = "ccd", consumer = "divorce_caseMaintenanceService_caseworker")
Please change provider to "ccdDataStoreAPI_CaseController" and consumer to "divorce_caseMaintenanceService"

2020-12-09 15:24 UTC, ruban72 approved these changes

2021-01-05 10:33 UTC, yarpo commented on build.gradle
> +    integrationTestImplementation('org.junit.jupiter:junit-jupiter-api:5.3.2')
why don't we use 5.7?

Dependabot is updating it automatically:
https://github.com/hmcts/div-case-orchestration-service/pull/1108

2021-01-05 10:36 UTC, yarpo commented on dependency-check-suppressions.xml
> +        <cve>CVE-2020-15250</cve>
why? Have you tried to update junit package to >= 4.13.1?

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250

2021-01-05 10:37 UTC, yarpo commented on gradle/wrapper/gradle-wrapper.properties
> +#Tue Nov 03 14:38:31 GMT 2020
is this line needed?

2021-01-05 10:37 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/DraftStoreClientConsumerTest.java
> +public class DraftStoreClientConsumerTest  {
please remove this redundant space

2021-01-05 10:37 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +        // @formatter:off
why?

2021-01-05 10:37 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +            .path("/caseworkers/"
why don't you have a method / builder for this string?

2021-01-05 10:38 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +            .headers(HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN, SERVICE_AUTHORIZATION,
wouldn't be that better:

```
.headers(
    HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN,
   SERVICE_AUTHORIZATION, SOME_SERVICE_AUTHORIZATION_TOKEN
)
```

?

2021-01-05 10:39 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +            .matchHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
I may be wrong, but this looks weird to me. The same line 2 lines above is correct?

2021-01-05 10:40 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +        CaseDetails caseDetailsReponse = coreCaseDataApi.readForCaseWorker(SOME_AUTHORIZATION_TOKEN,
```
coreCaseDataApi.readForCaseWorker(
    SOME_AUTHORIZATION_TOKEN,
    SOME_SERVICE_AUTHORIZATION_TOKEN,
    USER_ID,
    jurisdictionId,
    caseType,
    CASE_ID.toString()
);
```

seems to be more consistent with our formatting standards.

2021-01-05 10:40 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +
redundant empty line. Please remove

2021-01-05 10:40 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCitizenConsumerTest.java
> +
redundant empty line. Please remove.

2021-01-05 10:41 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCitizenConsumerTest.java
> +            .path("/citizens/"
as above - method / builder.

2021-01-05 10:41 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCitizenConsumerTest.java
> +            .headers(HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN, SERVICE_AUTHORIZATION,
as above.

2021-01-05 10:41 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCitizenConsumerTest.java
> +    RequestResponsePact readForCitizen(PactDslWithProvider builder) {
How much this fragment of code is different than the previous one? Is there any way to re-use it?

2021-01-05 10:42 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCitizenConsumerTest.java
> +
redundant empty line.

2021-01-05 10:43 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchCasesConsumerTest.java
> +        queryString = ResourceLoader.loadJson(VALID_QUERY);
it will be the very same value each time.

Why is this `BeforeEach` and not just `Before`? [called once, as far as I know]

2021-01-05 10:43 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchCasesConsumerTest.java
> +            .headers(HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN, SERVICE_AUTHORIZATION,
as above

2021-01-05 10:44 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchCasesConsumerTest.java
> +        assertEquals(searchResult.getTotal(), 123);
where `123` does come from? Can you please make it a const and give it a self-descriptive name?

2021-01-05 10:44 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchCasesConsumerTest.java
> +        assertCaseDetails(searchResult.getCases().get(0)); // CaseDetail-1
what is "CaseDetail-1"?

2021-01-05 10:45 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +        Thread.sleep(2000);
I'm not sure why is this even needed, but if so - can you please move it to config file so that it can be easily setup in one place for all pact test classes?

2021-01-05 10:45 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +            .path("/citizens/"
as above

2021-01-05 10:45 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +            .headers(HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN, SERVICE_AUTHORIZATION,
as above

2021-01-05 10:46 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +            .query("")
what `""` here means? Can we please have a const with self-descriptive name, eg:

```
NO_QUERY_PARAMS = ""
```

2021-01-05 10:47 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +                buildNewListOfCaseDetailsDsl(20000000L))
why `20000000L`? Can this be more or less?

Can you please make it a const with name that explain the usage?

2021-01-05 10:47 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +        List<CaseDetails> caseDetailsList = coreCaseDataApi.searchForCitizen(SOME_AUTHORIZATION_TOKEN,
formatting.

2021-01-05 10:47 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchForCitizenConsumerTest.java
> +
redundant empty line

2021-01-05 10:47 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/StartEventForCaseWorkerConsumerTest.java
> +        Thread.sleep(2000);
const in config, please

2021-01-05 10:48 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/StartEventForCaseWorkerConsumerTest.java
> +            .headers(HttpHeaders.AUTHORIZATION, SOME_AUTHORIZATION_TOKEN, SERVICE_AUTHORIZATION, SOME_SERVICE_AUTHORIZATION_TOKEN)
formatting

2021-01-05 10:48 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/StartEventForCaseWorkerConsumerTest.java
> +        // @formatter:off
I think this code can be refactored the way this annotation will not be needed anymore.

2021-01-05 10:49 UTC, yarpo commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/StartEventForCitizenConsumerTest.java
> +public class StartEventForCitizenConsumerTest extends CcdConsumerTestBase {
I have a feeling I'm adding the very same comments to all classes. Please address my comments from above to classes below as well.

2021-02-17 10:22 UTC, yarpo commented
I'm closing, please reopen if needed.

2021-03-23 10:01 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/ReadForCaseWorkerConsumerTest.java
> +            .matchHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
The 2 lines are different actually. The first defines the headers for the request and the second for the response

2021-03-23 10:02 UTC, ruban72 commented on src/contractTest/java/uk/gov/hmcts/reform/divorce/casemaintenanceservice/client/ccd/SearchCasesConsumerTest.java
> +        queryString = ResourceLoader.loadJson(VALID_QUERY);
This needs to be a @BeforeEach for the test to work.

2021-03-23 13:01 UTC, yarpo commented on build.gradle
> +    contractTestCompile group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: versions.junit_jupiter
can you please rename the var: 

```
junit_jupiter -> junitJupiter
```

?

2021-03-23 13:01 UTC, yarpo approved these changes

2021-03-26 14:48 UTC, merged